In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

In [2]:
# Print statement check tensorflow is running
print(tf. __version__)
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
print((tf.random.normal([2, 2])))

2.10.0
tf.Tensor(-723.40027, shape=(), dtype=float32)
tf.Tensor(
[[0.38133493 0.5799184 ]
 [0.34678766 0.09508794]], shape=(2, 2), dtype=float32)


In [3]:
# Tensorflow Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print("Initialize TF Scalar : " + str(x))

Initialize TF Scalar : tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
# Tensorflow Initialization
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print("Initialize TF Array : ") 
print(x)

x = tf.eye(3)
print("Initialize TF Array - Identity Matrix : ") 
print(x)


x = tf.ones((4, 3))
print("Initialize TF Array - ones : ") 
print(x)

x = tf.zeros((3, 2, 5))
print("Initialize TF Array - zeros : ") 
print(x)

x = tf.random.uniform((2, 2), minval=0, maxval=1)
print("Initialize TF Array - uniform distribution : ")
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print("Initialize TF Array - normal distribution : ")
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print("Initialize TF Array - range : ")
print(x)

print("############--------END--------############")

Initialize TF Array : 
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Initialize TF Array - Identity Matrix : 
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
Initialize TF Array - ones : 
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
Initialize TF Array - zeros : 
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)
Initialize TF Array - uniform distribution : 
tf.Tensor(
[[0.939914   0.104954  ]
 [0.8564042  0.82511175]], shape=(2, 2), dtype=float32)
Initialize TF Array - normal distribution : 
tf.Tensor(
[[-0.83567715 -0.71482295  0.72993928]
 [ 0.48653027  0.90715468 -0.02969942]
 [-0.67989898 -1.29693723 -0.27238828]], shape=(3, 3), dtype=float64)
Initialize TF Array - range : 
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
############--------END--------############


In [5]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)

z = x ** 5

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y

x = tf.random.normal((2, 2))

# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

# Reshaping
x = tf.range(9)

x = tf.reshape(x, (3, 3))

x = tf.transpose(x, perm=[1, 0])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
